const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generatePDF = (hostel) => {
  const doc = new PDFDocument({ margin: 50 });

  // Ensure the PDF directory exists
  const directory = path.join(__dirname, '../pdfs');
  if (!fs.existsSync(directory)) {
    fs.mkdirSync(directory, { recursive: true });
  }

  // Path to save the PDF
  const fileName = `${hostel.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}-brochure.pdf`;
  const filePath = path.join(directory, fileName);
  console.log('Creating PDF at:', filePath);
  const writeStream = fs.createWriteStream(filePath);
  doc.pipe(writeStream);

  // Add Title
  doc
    .fontSize(24)
    .text(hostel.name, {
      align: 'center',
      underline: true,
    })
    .moveDown(2);

  // Add Hostel Information
  doc
    .fontSize(18)
    .fillColor('#333')
    .text(`Price:  ${hostel.price}`, { align: 'left' })
    .moveDown();

  doc
    .fontSize(12)
    .fillColor('#555')
    .text(`Location: ${hostel.address}, ${hostel.city}, ${hostel.state}, ${hostel.country}`)
    .moveDown();

  doc
    .fontSize(12)
    .fillColor('#555')
    .text(`Description: ${hostel.description}`)
    .moveDown();

  doc
    .fontSize(12)
    .fillColor('#555')
    .text(`Sharing: ${hostel.sharing}`)
    .moveDown();

  doc
    .fontSize(12)
    .fillColor('#555')
    .text(`Bathrooms: ${hostel.bathrooms}`)
    .moveDown();

  doc
    .fontSize(12)
    .fillColor('#555')
    .text(`Floor Area: ${hostel.floorArea} sq. ft.`)
    .moveDown();

  doc
    .fontSize(12)
    .fillColor('#555')
    .text(`Total Beds: ${hostel.totalBeds}`)
    .moveDown();

  doc
    .fontSize(12)
    .fillColor('#555')
    .text(`Amenities: ${hostel.amenities.join(', ')}`)
    .moveDown(2);

  // Add Footer
  doc
    .fontSize(10)
    .fillColor('#777')
    .text('Generated by StayEasy', { align: 'center' })
    .moveDown();

  // Finalize PDF and end the stream
  doc.end();

  // Ensure the file exists after completion
  const checkFilePath = path.join(directory, fileName);
  writeStream.on('finish', () => {
    if (fs.existsSync(checkFilePath)) {
      console.log('PDF created successfully:', checkFilePath);
    } else {
      console.error('PDF file not found after creation:', checkFilePath);
    }
  });

  return filePath;
};

module.exports = generatePDF;
